### ISSUE TITLE
Unable to build on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by guighub** [VDavid003/sm64-port-android-base#76]
I followed the Linux building instructions and it failed to build compile after running ``make --jobs 4`` with the following text:

```gmake: gcc: No such file or directory
gmake: *** [Makefile:66: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/guiguig/sm64-port-android-base/app/jni/src/./extract_assets.py", line 292, in <module>
    main()
  File "/home/guiguig/sm64-port-android-base/app/jni/src/./extract_assets.py", line 162, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gmake', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:183: *** Failed to extract assets.  Stop.
```

I tried compiling on Windows and Termux as well but they gave different errors too, Windows failed on running the gradlew.bat command and Termux failed to locate one of the audio libraries.

**Comment by Honest-n** [comment]
The build instructions for termux are incomplete and I've never successfully mangaged to build for android on anything other than android
You need to install binutils and download krhplatform.h from kronos.
I've added a commit but it has yet to be merged.
See https://github.com/VDavid003/sm64-port-android/blob/653e11d84ffeef9c5c264c78087f0648242274d1/README.md

**Comment by guighub** [comment]
On Termux I still get this error:

```
In file included from src/pc/gfx/gfx_sdl2.c:19:
SDL/include/SDL2/SDL_opengles2.h:35:10: fatal error: 'GLES2/gl2platform.h' file not found
#include <GLES2/gl2platform.h>
```

**Comment by Honest-n** [comment]
This should be included with the ndk-sysroot package that should have installed with the clang package
